5 header and footer
GSG-FC02/CovidApp pull request #6
Opened 2021-04-09 13:51 UTC by sajaabusafiah

- create a header section
- create a footer section
- add footer icons
 ---
note 👍 
you need to change the href in the links

2021-04-10 12:39 UTC, Ibrahim-Jarada approved these changes, later dismissed
Its better to use h1 with header text  like this <header><h1>Covid App</h1></header>

2021-04-10 13:28 UTC, Tuqa-yasin approved these changes, later dismissed

2021-04-10 14:03 UTC, abdullahMuzyed approved these changes, later dismissed

2021-04-11 04:28 UTC, sara219 requested changes

2021-04-11 04:28 UTC, sara219 commented on css/search.css
> +  width: 100%;
https://github.com/GSG-FC02/CovidApp/blob/f48ee67d90dfbbdbfe2fa798a440a4d0923307b3/css/search.css#L53-L58

repeated width, delete one of them :

2021-04-11 07:21 UTC, Ibrahim-Jarada approved these changes

2021-04-11 07:23 UTC, sara219 approved these changes

2021-04-11 07:34 UTC, abdullahMuzyed approved these changes

2021-04-11 07:35 UTC, merged